# Generated by Django 2.1.7 on 2019-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorsFeuilleDeRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default=1, max_length=128)),
                ('priorite', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=2)),
                ('etat', models.BooleanField(default=False)),
                ('status', models.CharField(default=1, max_length=32)),
                ('commentaire', models.CharField(default=1, max_length=256)),
                ('budget', models.DecimalField(decimal_places=1, default=0, max_digits=40)),
                ('duree', models.CharField(default=2, max_length=32)),
                ('type', models.CharField(default=1, max_length=32)),
            ],
        ),
    ]
