# Generated by Django 2.1.7 on 2019-06-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feuillederoute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuillederoute',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.Direction'),
        ),
        migrations.AlterField(
            model_name='feuillederoute',
            name='type',
            field=models.CharField(choices=[('FeuilleDeRoute', 'FeuilleDeRoute'), ('HorsFeuilleDeRoute', 'HorsFeuilleDeRoute')], max_length=32),
        ),
    ]
