# Generated by Django 2.1.7 on 2019-06-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feuillederoute', '0002_auto_20190624_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuillederoute',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membre.Membre'),
        ),
    ]
